import 'package:drop_down_list/model/selected_list_item.dart';

class Cities {
  static List<SelectedListItem> cityList = [
    SelectedListItem(name: 'Ambon'),
    SelectedListItem(name: 'Bali'),
    SelectedListItem(name: 'Balikpapan'),
    SelectedListItem(name: 'Banda Aceh'),
    SelectedListItem(name: 'Bandar Lampung'),
    SelectedListItem(name: 'Bandung'),
    SelectedListItem(name: 'Bangka'),
    SelectedListItem(name: 'Bangkalan'),
    SelectedListItem(name: 'Bangu'),
    SelectedListItem(name: 'Bantul'),
    SelectedListItem(name: 'Banyuwangi'),
    SelectedListItem(name: 'Baubau'),
    SelectedListItem(name: 'Bekasi'),
    SelectedListItem(name: 'Bengkulu'),
    SelectedListItem(name: 'Bima'),
    SelectedListItem(name: 'Binjai'),
    SelectedListItem(name: 'Bitung'),
    SelectedListItem(name: 'Blitar'),
    SelectedListItem(name: 'Bogor'),
    SelectedListItem(name: 'Bondowoso'),
    SelectedListItem(name: 'Bontang'),
    SelectedListItem(name: 'Boyolali'),
    SelectedListItem(name: 'Bukittinggi'),
    SelectedListItem(name: 'Cilegon'),
    SelectedListItem(name: 'Cimahi'),
    SelectedListItem(name: 'Cirebon'),
    SelectedListItem(name: 'Denpasar'),
    SelectedListItem(name: 'Depok'),
    SelectedListItem(name: 'Donggala'),
    SelectedListItem(name: 'Dumai'),
    SelectedListItem(name: 'Ende'),
    SelectedListItem(name: 'Gorontalo'),
    SelectedListItem(name: 'Gunung Kidul'),
    SelectedListItem(name: 'Jakarta'),
    SelectedListItem(name: 'Jambi'),
    SelectedListItem(name: 'Jayapura'),
    SelectedListItem(name: 'Jember'),
    SelectedListItem(name: 'Jepara'),
    SelectedListItem(name: 'Jombang'),
    SelectedListItem(name: 'Kediri'),
    SelectedListItem(name: 'Kendari'),
    SelectedListItem(name: 'Kepahiang'),
    SelectedListItem(name: 'Klaten'),
    SelectedListItem(name: 'Kotamobagu'),
    SelectedListItem(name: 'Kudus'),
    SelectedListItem(name: 'Kupang'),
    SelectedListItem(name: 'Kuta'),
    SelectedListItem(name: 'Lahat'),
    SelectedListItem(name: 'Lamongan'),
    SelectedListItem(name: 'Lhokseumawe'),
    SelectedListItem(name: 'Lubuklinggau'),
    SelectedListItem(name: 'Lumajang'),
    SelectedListItem(name: 'Madiun'),
    SelectedListItem(name: 'Magelang'),
    SelectedListItem(name: 'Majene'),
    SelectedListItem(name: 'Makassar'),
    SelectedListItem(name: 'Malang'),
    SelectedListItem(name: 'Manado'),
    SelectedListItem(name: 'Mataram'),
    SelectedListItem(name: 'Maumere'),
    SelectedListItem(name: 'Medan'),
    SelectedListItem(name: 'Metro'),
    SelectedListItem(name: 'Mimika'),
    SelectedListItem(name: 'Mojo'),
    SelectedListItem(name: 'Mojokerto'),
    SelectedListItem(name: 'Padang'),
    SelectedListItem(name: 'Padang Panjang'),
    SelectedListItem(name: 'Pagar Alam'),
    SelectedListItem(name: 'Palangkaraya'),
    SelectedListItem(name: 'Palembang'),
    SelectedListItem(name: 'Palopo'),
    SelectedListItem(name: 'Palu'),
    SelectedListItem(name: 'Pamekasan'),
    SelectedListItem(name: 'Pandeglang'),
    SelectedListItem(name: 'Pangkal Pinang'),
    SelectedListItem(name: 'Pare-Pare'),
    SelectedListItem(name: 'Pariaman'),
    SelectedListItem(name: 'Pasuruan'),
    SelectedListItem(name: 'Payakumbuh'),
    SelectedListItem(name: 'Pekalongan'),
    SelectedListItem(name: 'Pekanbaru'),
    SelectedListItem(name: 'Pematang Siantar'),
    SelectedListItem(name: 'Pontianak'),
    SelectedListItem(name: 'Prabumulih'),
    SelectedListItem(name: 'Probolinggo'),
    SelectedListItem(name: 'Rantau'),
    SelectedListItem(name: 'Salatiga'),
    SelectedListItem(name: 'Samarinda'),
    SelectedListItem(name: 'Sampang'),
    SelectedListItem(name: 'Semarang'),
    SelectedListItem(name: 'Serang'),
    SelectedListItem(name: 'Sidoarjo'),
    SelectedListItem(name: 'Singaraja'),
    SelectedListItem(name: 'Singkawang'),
    SelectedListItem(name: 'Situbondo'),
    SelectedListItem(name: 'Solok'),
    SelectedListItem(name: 'Sorong'),
    SelectedListItem(name: 'Sragen'),
    SelectedListItem(name: 'Subulussalam'),
    SelectedListItem(name: 'Sukabumi'),
    SelectedListItem(name: 'Sungai Penuh'),
    SelectedListItem(name: 'Surabaya'),
    SelectedListItem(name: 'Surakarta'),
    SelectedListItem(name: 'Tangerang'),
    SelectedListItem(name: 'Tanjung Balai'),
    SelectedListItem(name: 'Tanjung Pandan'),
    SelectedListItem(name: 'Tanjung Pinang'),
    SelectedListItem(name: 'Tangerang Selatan'),
    SelectedListItem(name: 'Tanjungbalai'),
    SelectedListItem(name: 'Tarakan'),
    SelectedListItem(name: 'Tebing Tinggi'),
    SelectedListItem(name: 'Tegal'),
    SelectedListItem(name: 'Ternate'),
    SelectedListItem(name: 'Tidore Kepulauan'),
    SelectedListItem(name: 'Tomohon'),
    SelectedListItem(name: 'Tondano'),
    SelectedListItem(name: 'Tual'),
    SelectedListItem(name: 'Tuban'),
    SelectedListItem(name: 'Tulungagung'),
    SelectedListItem(name: 'Ungaran'),
    SelectedListItem(name: 'Waikabubak'),
    SelectedListItem(name: 'Waingapu'),
    SelectedListItem(name: 'Watampone'),
    SelectedListItem(name: 'Watansoppeng'),
    SelectedListItem(name: 'Yogyakarta'),
  ];

  static List<String> kotaList = [
    'Ambon',
    'Bali',
    'Balikpapan',
    'Banda Aceh',
    'Bandar Lampung',
    'Bandung',
    'Bangka',
    'Bangkalan',
    'Bangu',
    'Bantul',
    'Banyuwangi',
    'Baubau',
    'Bekasi',
    'Bengkulu',
    'Bima',
    'Binjai',
    'Bitung',
    'Blitar',
    'Bogor',
    'Bondowoso',
    'Bontang',
    'Boyolali',
    'Bukittinggi',
    'Cilegon',
    'Cimahi',
    'Cirebon',
    'Denpasar',
    'Depok',
    'Donggala',
    'Dumai',
    'Ende',
    'Gorontalo',
    'Gunung Kidul',
    'Jakarta',
    'Jambi',
    'Jayapura',
    'Jember',
    'Jepara',
    'Jombang',
    'Kediri',
    'Kendari',
    'Kepahiang',
    'Klaten',
    'Kotamobagu',
    'Kudus',
    'Kupang',
    'Kuta',
    'Lahat',
    'Lamongan',
    'Lhokseumawe',
    'Lubuklinggau',
    'Lumajang',
    'Madiun',
    'Magelang',
    'Majene',
    'Makassar',
    'Malang',
    'Manado',
    'Mataram',
    'Maumere',
    'Medan',
    'Metro',
    'Mimika',
    'Mojo',
    'Mojokerto',
    'Padang',
    'Padang Panjang',
    'Pagar Alam',
    'Palangkaraya',
    'Palembang',
    'Palopo',
    'Palu',
    'Pamekasan',
    'Pandeglang',
    'Pangkal Pinang',
    'Pare-Pare',
    'Pariaman',
    'Pasuruan',
    'Payakumbuh',
    'Pekalongan',
    'Pekanbaru',
    'Pematang Siantar',
    'Pontianak',
    'Prabumulih',
    'Probolinggo',
    'Rantau',
    'Salatiga',
    'Samarinda',
    'Sampang',
    'Semarang',
    'Serang',
    'Sidoarjo',
    'Singaraja',
    'Singkawang',
    'Situbondo',
    'Solok',
    'Sorong',
    'Sragen',
    'Subulussalam',
    'Sukabumi',
    'Sungai Penuh',
    'Surabaya',
    'Surakarta',
    'Tangerang',
    'Tanjung Balai',
    'Tanjung Pandan',
    'Tanjung Pinang',
    'Tangerang Selatan',
    'Tanjungbalai',
    'Tarakan',
    'Tebing Tinggi',
    'Tegal',
    'Ternate',
    'Tidore Kepulauan',
    'Tomohon',
    'Tondano',
    'Tual',
    'Tuban',
    'Tulungagung',
    'Ungaran',
    'Waikabubak',
    'Waingapu',
    'Watampone',
    'Watansoppeng',
    'Yogyakarta',
  ];
}
