import 'package:drop_down_list/model/selected_list_item.dart';

class Jobs {
  static List<SelectedListItem> jobList = [
    SelectedListItem(name: 'Belum/Tidak Bekerja'),
    SelectedListItem(name: 'Mengurus Rumah Tangga'),
    SelectedListItem(name: 'Pelajar/Mahasiswa'),
    SelectedListItem(name: 'Pensiunan'),
    SelectedListItem(name: 'Pegawai Negeri Sipil'),
    SelectedListItem(name: 'Tentara Nasional Indonesia'),
    SelectedListItem(name: 'Kepolisisan RI'),
    SelectedListItem(name: 'Perdagangan'),
    SelectedListItem(name: 'Petani/Pekebun'),
    SelectedListItem(name: 'Peternak'),
    SelectedListItem(name: 'Nelayan/Perikanan'),
    SelectedListItem(name: 'Industri'),
    SelectedListItem(name: 'Konstruksi'),
    SelectedListItem(name: 'Transportasi'),
    SelectedListItem(name: 'Karyawan Swasta'),
    SelectedListItem(name: 'Karyawan BUMN'),
    SelectedListItem(name: 'Karyawan BUMD'),
    SelectedListItem(name: 'Karyawan Honorer'),
    SelectedListItem(name: 'Buruh Harian Lepas'),
    SelectedListItem(name: 'Buruh Tani/Perkebunan'),
    SelectedListItem(name: 'Buruh Nelayan/Perikanan'),
    SelectedListItem(name: 'Buruh Peternakan'),
    SelectedListItem(name: 'Pembantu Rumah Tangga'),
    SelectedListItem(name: 'Tukang Cukur'),
    SelectedListItem(name: 'Tukang Listrik'),
    SelectedListItem(name: 'Tukang Batu'),
    SelectedListItem(name: 'Tukang Kayu'),
    SelectedListItem(name: 'Tukang Sol Sepatu'),
    SelectedListItem(name: 'Tukang Las/Pandai Besi'),
    SelectedListItem(name: 'Tukang Jahit'),
    SelectedListItem(name: 'Tukang Gigi'),
    SelectedListItem(name: 'Penata Rias'),
    SelectedListItem(name: 'Penata Busana'),
    SelectedListItem(name: 'Penata Rambut'),
    SelectedListItem(name: 'Mekanik'),
    SelectedListItem(name: 'Seniman'),
    SelectedListItem(name: 'Tabib'),
    SelectedListItem(name: 'Paraji'),
    SelectedListItem(name: 'Perancang Busana'),
    SelectedListItem(name: 'Penterjemah'),
    SelectedListItem(name: 'Imam Masjid'),
    SelectedListItem(name: 'Pendeta'),
    SelectedListItem(name: 'Pastor'),
    SelectedListItem(name: 'Wartawan'),
    SelectedListItem(name: 'Ustadz/Mubaligh'),
    SelectedListItem(name: 'Juru Masak'),
    SelectedListItem(name: 'Promotor Acara'),
    SelectedListItem(name: 'Anggota DPR-RI'),
    SelectedListItem(name: 'Anggota DPD'),
    SelectedListItem(name: 'Anggota BPK'),
    SelectedListItem(name: 'Presiden'),
    SelectedListItem(name: 'Wakil Presiden'),
    SelectedListItem(name: 'Anggota Mahkamah Konstitusi'),
    SelectedListItem(name: 'Anggota Kabinet/Kementerian'),
    SelectedListItem(name: 'Duta Besar'),
    SelectedListItem(name: 'Gubernur'),
    SelectedListItem(name: 'Wakil Gubernur'),
    SelectedListItem(name: 'Bupati'),
    SelectedListItem(name: 'Wakil Bupati'),
    SelectedListItem(name: 'Walikota'),
    SelectedListItem(name: 'Wakil Walikota'),
    SelectedListItem(name: 'Anggota DPRD Provinsi'),
    SelectedListItem(name: 'Anggota DPRD Kabupaten/Kota'),
    SelectedListItem(name: 'Dosen'),
    SelectedListItem(name: 'Guru'),
    SelectedListItem(name: 'Pilot'),
    SelectedListItem(name: 'Pengacara'),
    SelectedListItem(name: 'Notaris'),
    SelectedListItem(name: 'Arsitek'),
    SelectedListItem(name: 'Akuntan'),
    SelectedListItem(name: 'Konsultan'),
    SelectedListItem(name: 'Dokter'),
    SelectedListItem(name: 'Bidan'),
    SelectedListItem(name: 'Perawat'),
    SelectedListItem(name: 'Apoteker'),
    SelectedListItem(name: 'Psikiater/Psikolog'),
    SelectedListItem(name: 'Penyiar Televisi'),
    SelectedListItem(name: 'Penyiar Radio'),
    SelectedListItem(name: 'Pelaut'),
    SelectedListItem(name: 'Peneliti'),
    SelectedListItem(name: 'Sopir'),
    SelectedListItem(name: 'Pialang'),
    SelectedListItem(name: 'Paranormal'),
    SelectedListItem(name: 'Pedagang'),
    SelectedListItem(name: 'Perangkat Desa'),
    SelectedListItem(name: 'Kepala Desa'),
    SelectedListItem(name: 'Biarawati'),
    SelectedListItem(name: 'Wiraswasta'),
  ];
}
