import 'package:drop_down_list/model/selected_list_item.dart';

class Provinsi {
  static List<SelectedListItem> provinsiList = [
    SelectedListItem(name: 'Aceh'),
    SelectedListItem(name: 'Bali'),
    SelectedListItem(name: 'Banten'),
    SelectedListItem(name: 'Bengkulu'),
    SelectedListItem(name: 'Gorontalo'),
    SelectedListItem(name: 'DKI Jakarta'),
    SelectedListItem(name: 'Jambi'),
    SelectedListItem(name: 'Jawa Barat'),
    SelectedListItem(name: 'Jawa Tengah'),
    SelectedListItem(name: 'Jawa Timur'),
    SelectedListItem(name: 'Kalimantan Barat'),
    SelectedListItem(name: 'Kalimantan Selatan'),
    SelectedListItem(name: 'Kalimantan Tengah'),
    SelectedListItem(name: 'Kalimantan Timur'),
    SelectedListItem(name: 'Kalimantan Utara'),
    SelectedListItem(name: 'Kepulauan Bangka Belitung'),
    SelectedListItem(name: 'Kepulauan Riau'),
    SelectedListItem(name: 'Lampung'),
    SelectedListItem(name: 'Maluku'),
    SelectedListItem(name: 'Maluku Utara'),
    SelectedListItem(name: 'Nanggroe Aceh Darussalam (NAD)'),
    SelectedListItem(name: 'Nusa Tenggara Barat (NTB)'),
    SelectedListItem(name: 'Nusa Tenggara Timur (NTT)'),
    SelectedListItem(name: 'Papua'),
    SelectedListItem(name: 'Papua Barat'),
    SelectedListItem(name: 'Riau'),
    SelectedListItem(name: 'Sulawesi Barat'),
    SelectedListItem(name: 'Sulawesi Selatan'),
    SelectedListItem(name: 'Sulawesi Tengah'),
    SelectedListItem(name: 'Sulawesi Tenggara'),
    SelectedListItem(name: 'Sulawesi Utara'),
    SelectedListItem(name: 'Sumatera Barat'),
    SelectedListItem(name: 'Sumatera Selatan'),
    SelectedListItem(name: 'Sumatera Utara'),
    SelectedListItem(name: 'Yogyakarta'),
  ];
}
